spring.application.name=shrii_bank_Backend

# PostgreSQL Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/shrii_bank_db
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Port
server.port=8080